"""
Pydantic models shared across the application.

Organised by domain:
  - Auth         (users, tokens)
  - SoW          (documents, sections)
  - Content      (content, scope, pricing, assumptions, resources)
  - AI Suggestion
  - History / Collaboration
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

# ── Auth ─────────────────────────────────────────────────────────────────────


class UserResponse(BaseModel):
    """Safe representation of a user (no password)."""

    id: int
    email: str
    full_name: str | None = None
    username: str | None = None
    name: str | None = None
    role: str
    is_active: bool
    created_at: datetime
    oid: str | None = None  # Microsoft Entra object ID


# ── Content child-table models  (PDF §2.2.1 – 2.2.4) ─────────────────────────


class ScopeRecord(BaseModel):
    """Scope table row — PDF §2.2.1."""

    id: int
    content_id: int | None = None
    in_scope: list[Any] | None = None
    out_scope: list[Any] | None = None


class PricingRecord(BaseModel):
    """Pricing table row — PDF §2.2.2."""

    id: int
    content_id: int | None = None
    total_value: float | None = None
    breakdown: list[Any] | None = None


class AssumptionsRecord(BaseModel):
    """Assumptions table row — PDF §2.2.3."""

    id: int
    content_id: int | None = None
    items: list[Any] | None = None


class ResourcesRecord(BaseModel):
    """Resources table row — PDF §2.2.4."""

    id: int
    content_id: int | None = None
    team: list[Any] | None = None


class ContentRecord(BaseModel):
    """Content table row — PDF §2.2."""

    id: int
    scope_id: int | None = None
    price_id: int | None = None
    assumption_id: int | None = None
    resource_id: int | None = None


# ── AI Suggestion  (PDF §2.3) ────────────────────────────────────────────────


class AISuggestion(BaseModel):
    """AI Suggestion table row — PDF §2.3."""

    id: int
    flag: str | None = None  # Green / Yellow / Red
    validation_recommendation: dict[str, Any] | None = None
    risks: list[Any] | None = None


# ── SoW ──────────────────────────────────────────────────────────────────────


class SoWCreate(BaseModel):
    """Payload for creating a new SoW document.

    ``cycle`` tracks which deal cycle (1–4) the SoW is in (PDF §2.1).
    ``client_id`` is the optional string ID generated by the frontend for
    backward-compatibility with localStorage state; omit it when the frontend
    posts to the backend first (the preferred flow).
    """

    title: str = Field(min_length=1)
    cycle: int | None = Field(
        default=1,
        ge=1,
        le=4,
        description="Deal cycle 1–4 (PDF §2.1)",
    )
    client_id: str | None = Field(
        default=None,
        description="Frontend-generated string ID (legacy/offline fallback)",
    )
    methodology: str | None = None
    customer_name: str | None = None
    opportunity_id: str | None = None
    deal_value: float | None = None
    estimated_margin: float | None = None
    content: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    workflow_template_id: int | None = Field(
        default=None,
        description="Workflow template ID; defaults to the system default template",
    )
    content_template_id: int | None = Field(
        default=None,
        description="Content template ID for pre-populated section content",
    )


class SoWUpdate(BaseModel):
    """Partial update payload — any field is optional."""

    title: str | None = Field(default=None, min_length=1)
    cycle: int | None = Field(default=None, ge=1, le=4)
    status: str | None = None
    methodology: str | None = None
    customer_name: str | None = None
    opportunity_id: str | None = None
    deal_value: float | None = None
    estimated_margin: float | None = None
    content: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None


class SoWStatusUpdate(BaseModel):
    """Payload for updating only the SoW status."""

    status: str = Field(description="e.g. draft, in_review, approved, rejected")


class SoWResponse(BaseModel):
    """Full SoW document representation returned from the API."""

    id: int
    title: str
    status: str
    cycle: int | None = None
    content_id: int | None = None
    ai_suggestion_id: int | None = None
    esap_level: str | None = None
    estimated_margin: float | None = None
    uploaded_at: datetime
    updated_at: datetime
    client_id: str | None = None
    methodology: str | None = None
    customer_name: str | None = None
    opportunity_id: str | None = None
    deal_value: float | None = None
    content: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    finalized_at: datetime | None = None
    finalized_by: int | None = None


class SoWSummary(BaseModel):
    """Lightweight SoW entry returned in list responses."""

    id: int
    title: str
    status: str
    cycle: int | None = None
    methodology: str | None = None
    customer_name: str | None = None
    opportunity_id: str | None = None
    deal_value: float | None = None
    esap_level: str | None = None
    estimated_margin: float | None = None
    client_id: str | None = None
    updated_at: datetime


# ── History / Collaboration  (PDF §2.4, §2.5) ────────────────────────────────


class HistoryEntry(BaseModel):
    """History audit log row — PDF §2.4."""

    id: int
    sow_id: int | None = None
    changed_by: int | None = None
    change_type: str | None = None
    changed_at: datetime
    diff: dict[str, Any] | None = None


class HistoryEntryResponse(BaseModel):
    """History entry with SoW title for user-centric history views."""

    id: int
    sow_id: int | None = None
    changed_by: int | None = None
    change_type: str | None = None
    changed_at: datetime
    diff: dict[str, Any] | None = None
    sow_title: str | None = None


class CollaborationEntry(BaseModel):
    """Collaboration (user↔SOW role) row — PDF §2.5."""

    id: int
    sow_id: int | None = None
    user_id: int
    role: str | None = None


# ── Document Parsing ────────────────────────────────────────────────────────


class SectionResult(BaseModel):
    """Result of detecting a single required section in an uploaded document."""

    name: str
    displayName: str
    found: bool
    content: str | None = None
    issues: list[str] = []


class ParseResult(BaseModel):
    """Result of parsing an uploaded SoW document against methodology rules."""

    sections: list[SectionResult]
    missingKeywords: list[str] = []
    violations: list[dict[str, Any]] = []


# ── AI Analysis  (Phase 1) ──────────────────────────────────────────────────


class ViolationResult(BaseModel):
    """A single rule violation found in the SoW."""

    rule: str
    severity: str  # "high", "medium", "low"
    message: str
    section: str | None = None


class RiskResult(BaseModel):
    """A single identified risk."""

    category: str  # "Staffing", "Timeline", "Budget", etc.
    level: str  # "high", "medium", "low"
    description: str


class ApprovalRouting(BaseModel):
    """AI-determined approval routing recommendation."""

    level: str  # "Green", "Yellow", "Red"
    esap_type: str  # "Type-1", "Type-2", "Type-3"
    reason: str
    chain: list[str]  # ["Solution Architect", "SQA Reviewer", ...]


class ChecklistSuggestion(BaseModel):
    """AI-suggested checklist item."""

    id: str
    text: str
    category: str
    required: bool
    auto_result: str | None = None  # "pass", "fail", "warning", None


class SectionSuggestion(BaseModel):
    """AI-suggested content improvement for a section."""

    section: str
    current_text: str | None = None
    suggested_text: str | None = None
    rationale: str | None = None


class AIAnalysisResult(BaseModel):
    """Complete AI analysis result for a SoW."""

    violations: list[ViolationResult]
    risks: list[RiskResult]
    approval: ApprovalRouting
    checklist: list[ChecklistSuggestion]
    suggestions: list[SectionSuggestion]
    overall_score: float | None = None  # 0-100
    summary: str | None = None


# ── Review  (Phase 2) ───────────────────────────────────────────────────────


class ReviewAssignment(BaseModel):
    """A single review assignment row."""

    id: int
    sow_id: int
    user_id: int
    reviewer_role: str
    stage: str
    status: str  # pending, in_progress, completed
    decision: str | None = None
    comments: str | None = None
    conditions: list[str] | None = None
    checklist_responses: list[dict[str, Any]] | None = None
    assigned_at: datetime
    completed_at: datetime | None = None


class ReviewAssignmentSummary(BaseModel):
    """Review assignment with joined SoW fields for list views."""

    id: int
    sow_id: int
    sow_title: str
    sow_status: str
    methodology: str | None = None
    customer_name: str | None = None
    deal_value: float | None = None
    esap_level: str | None = None
    reviewer_role: str
    stage: str
    status: str
    assigned_at: datetime
    completed_at: datetime | None = None


class ChecklistItemModel(BaseModel):
    """A single checklist item from review-checklists.json."""

    id: str
    text: str
    required: bool
    category: str
    help_text: str | None = Field(default=None, alias="helpText")

    model_config = {"populate_by_name": True}


class ReviewChecklistResponse(BaseModel):
    """Full checklist for a reviewer."""

    reviewer_role: str
    display_name: str
    focus_areas: list[str]
    items: list[ChecklistItemModel]
    saved_responses: list[dict[str, Any]] | None = None


class ReviewProgressPayload(BaseModel):
    """Partial save of review progress."""

    checklist_responses: list[dict[str, Any]]
    comments: str | None = None


class ReviewSubmitPayload(BaseModel):
    """Final review decision submission."""

    decision: str  # "approved", "rejected", "approved-with-conditions"
    checklist_responses: list[dict[str, Any]]
    comments: str | None = None
    conditions: list[str] | None = None


class ReviewAssignmentStatusSummary(BaseModel):
    """Summary of a single reviewer's status within a review."""

    reviewer_role: str
    display_name: str
    stage: str
    status: str
    decision: str | None = None
    completed_at: datetime | None = None


class ReviewStatus(BaseModel):
    """Aggregated review status for a SoW."""

    sow_id: int
    current_stage: str
    esap_level: str | None = None
    assignments: list[ReviewAssignmentStatusSummary]
    gating_rules_met: bool
    outstanding_requirements: list[str]


# ── Send-Back  (Phase 3) ────────────────────────────────────────────────────


class SendBackPayload(BaseModel):
    """Payload for sending a SoW back to a previous stage."""

    target_stage: str  # "draft" or "internal_review"
    comments: str
    action_items: list[str] | None = None


# ── Finalize & Handoff  (Phase 4) ───────────────────────────────────────────


class HandoffPackagePayload(BaseModel):
    """Input for creating a handoff package."""

    delivery_team: list[dict[str, Any]]
    key_contacts: list[dict[str, Any]]
    kickoff_date: str | None = None
    special_instructions: str | None = None
    notes: str | None = None


class HandoffPackageResponse(BaseModel):
    """Handoff package output."""

    id: int
    sow_id: int
    created_by: int | None = None
    document_path: str | None = None
    package_data: dict[str, Any]
    created_at: datetime


class DocumentGenerationResponse(BaseModel):
    """Result of document generation."""

    file_path: str
    file_name: str
    format: str
    size_bytes: int


# ── Workflow Templates ───────────────────────────────────────────────────────


class WorkflowStageRoleConfig(BaseModel):
    """A reviewer role required at a workflow stage."""

    role_key: str
    is_required: bool = True
    esap_levels: list[str] | None = None  # None = all levels


class WorkflowStageConfig(BaseModel):
    """A single stage within a workflow template."""

    stage_key: str
    display_name: str
    stage_order: int
    stage_type: str = "review"  # draft, ai_analysis, review, approval, terminal
    roles: list[WorkflowStageRoleConfig] = []
    config: dict[str, Any] = {}


class WorkflowTransitionConfig(BaseModel):
    """A valid transition between two stages."""

    from_stage: str
    to_stage: str


class WorkflowData(BaseModel):
    """Full workflow snapshot stored per-SoW."""

    stages: list[WorkflowStageConfig]
    transitions: list[WorkflowTransitionConfig]


class WorkflowTemplateCreate(BaseModel):
    """Payload for creating a new workflow template."""

    name: str = Field(min_length=1)
    description: str | None = None
    workflow_data: WorkflowData


class WorkflowTemplateResponse(BaseModel):
    """Full workflow template with stages, roles, and transitions."""

    id: int
    name: str
    description: str | None = None
    is_system: bool
    workflow_data: WorkflowData
    created_at: datetime


class WorkflowTemplateSummary(BaseModel):
    """Lightweight listing of a workflow template."""

    id: int
    name: str
    description: str | None = None
    is_system: bool
    stage_count: int = 0
    created_at: datetime


class SoWWorkflowResponse(BaseModel):
    """Per-SoW workflow instance."""

    id: int
    sow_id: int
    template_id: int | None = None
    current_stage: str
    workflow_data: WorkflowData
    created_at: datetime
    updated_at: datetime


# ── Conditions of Approval ───────────────────────────────────────────────────


class COACreate(BaseModel):
    """Payload for creating a Condition of Approval."""

    condition_text: str = Field(min_length=1)
    category: str = "general"  # technical, commercial, legal, staffing, general
    priority: str = "medium"  # low, medium, high, critical
    assigned_to: int | None = None
    due_date: str | None = None  # ISO date string (YYYY-MM-DD)


class COAUpdate(BaseModel):
    """Partial update payload for a COA."""

    condition_text: str | None = None
    category: str | None = None
    priority: str | None = None
    assigned_to: int | None = None
    due_date: str | None = None
    status: str | None = None
    resolution_notes: str | None = None


class COAResolvePayload(BaseModel):
    """Payload for resolving a COA."""

    resolution_notes: str = Field(min_length=1)


class COAWaivePayload(BaseModel):
    """Payload for waiving a COA."""

    resolution_notes: str = Field(min_length=1)


class COAResponse(BaseModel):
    """Full COA representation."""

    id: int
    sow_id: int
    review_assignment_id: int | None = None
    condition_text: str
    category: str
    priority: str
    assigned_to: int | None = None
    due_date: str | None = None
    status: str
    resolution_notes: str | None = None
    resolved_by: int | None = None
    resolved_at: datetime | None = None
    evidence: list[Any] = []
    created_by: int | None = None
    created_at: datetime
    updated_at: datetime


class COASummary(BaseModel):
    """Summary counts for all COAs on a SoW."""

    sow_id: int
    total: int
    open: int
    in_progress: int
    resolved: int
    waived: int
    blocks_finalization: bool


# ── Content Templates ────────────────────────────────────────────────────────


class ContentTemplateResponse(BaseModel):
    """A SoW content template with pre-populated bullet-point content."""

    id: int
    name: str
    methodology: str
    description: str | None = None
    template_data: dict[str, Any]
    is_system: bool
    created_at: datetime


# ── Attachments ──────────────────────────────────────────────────────────────


class AttachmentResponse(BaseModel):
    """Metadata for a file attached to a SoW."""

    id: int
    sow_id: int
    filename: str
    original_name: str
    file_size: int | None = None
    mime_type: str | None = None
    document_type: str
    stage_key: str | None = None
    description: str | None = None
    uploaded_by: int | None = None
    uploaded_at: datetime


class DocumentRequirement(BaseModel):
    """A single document requirement for a workflow stage."""

    document_type: str
    is_required: bool
    description: str | None = None
    fulfilled: bool = False


class StageRequirementsResponse(BaseModel):
    """Document requirements + fulfillment status for a SoW stage."""

    sow_id: int
    stage_key: str
    requirements: list[DocumentRequirement]
    all_required_met: bool
